JsConcepts/JsConcepts/Controllers/BaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ModelStore;

namespace JsConcepts.Controllers
{
    public class BaseController : Controller
    {
        protected InMemoryStore Store
        {
            get
            {
                return HttpContext.Application["Store"] as InMemoryStore;
            }
        }
    }
}

JsConcepts/JsConcepts/Controllers/BrowseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Model;
using Model.Projections;

namespace JsConcepts.Controllers
{
    public class BrowseController : BaseController
    {
        //
        // GET: /Browse/

        public ActionResult Index()
        {
            return View(Store.FetchAll<Contact>().AsContactBriefInfo()
                .OrderBy(c => c.FirstName)
                .ThenBy(c => c.LastName));
        }

    }
}

JsConcepts/JsConcepts/Controllers/ContactsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Model;
using Model.Projections;

namespace JsConcepts.Controllers
{
    public class ContactsController : BaseController
    {
        public ActionResult Index()
        {
            return View(Store.FetchAll<Contact>().AsContactBriefInfo());
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Contact contact)
        {
            Store.Store<Contact>(contact);
            return RedirectToAction("Index");
        }

        public ActionResult Edit(Guid id)
        {
            return View(Store.Fetch<Contact>(id));
        }

        [HttpPost]
        public ActionResult Edit(Contact contact)
        {
            Store.Store<Contact>(contact);
            return RedirectToAction("Index");
        }

        public ActionResult Delete(Guid id)
        {
            Store.Remove(id);
            return RedirectToAction("Index");
        }
    }
}

JsConcepts/JsConcepts/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JsConcepts.Controllers
{
    public class HomeController : BaseController
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

JsConcepts/JsConcepts/Views/Browse/Index.cshtml
@using Model.Projections
@model IEnumerable<ContactBriefInfo>
@{
    ViewBag.Title = "Browse Contacts";
    Layout = "~/Views/Shared/MainLayout.cshtml";
}

<h2>Browse Contacts</h2>

@foreach (ContactBriefInfo contact in Model)
{
    <div class="card">
        <h4>@contact.FirstName @contact.LastName</h4>
        <h6>@(contact.Company ?? "-")</h6>
    </div>
}

JsConcepts/JsConcepts/Views/Contacts/Create.cshtml
@model Model.Contact
@{
    ViewBag.Title = "Create Contact";
    Layout = "~/Views/Shared/MainLayout.cshtml";
}

<h2>Create Contact</h2>

@{Html.BeginForm();}

<ul class="noMark">
    <li>
        <label>
            First Name: 
            @Html.TextBoxFor(m => m.FirstName)
        </label>
    </li>
    <li>
        <label>
            Last Name: 
            @Html.TextBoxFor(m => m.LastName)
        </label>
    </li>
    <li>
        <label>
            Company: 
            @Html.TextBoxFor(m => m.Company)
        </label>
    </li>
    <li>
        <label>
            Phone: 
            @Html.TextBoxFor(m => m.PhoneNumber)
        </label>
    </li>
    <li>
        <label>
            Email: 
            @Html.TextBoxFor(m => m.EmailAddress)
        </label>
    </li>
    <li>
        <label>
            Address: 
            @Html.TextAreaFor(m => m.HomeAddress)
        </label>
    </li>
    <li>
        <button type="submit">Save</button>
    </li>
</ul>

@{Html.EndForm();}

JsConcepts/JsConcepts/Views/Contacts/Edit.cshtml
@model Model.Contact
@{
    ViewBag.Title = "Edit Contact";
    Layout = "~/Views/Shared/MainLayout.cshtml";
}

<h2>Edit</h2>

@{Html.BeginForm();}

@Html.HiddenFor(m => m.Id)

<ul class="noMark">
    <li>
        <label>
            First Name: 
            @Html.TextBoxFor(m => m.FirstName)
        </label>
    </li>
    <li>
        <label>
            Last Name: 
            @Html.TextBoxFor(m => m.LastName)
        </label>
    </li>
    <li>
        <label>
            Company: 
            @Html.TextBoxFor(m => m.Company)
        </label>
    </li>
    <li>
        <label>
            Phone: 
            @Html.TextBoxFor(m => m.PhoneNumber)
        </label>
    </li>
    <li>
        <label>
            Email: 
            @Html.TextBoxFor(m => m.EmailAddress)
        </label>
    </li>
    <li>
        <label>
            Address: 
            @Html.TextAreaFor(m => m.HomeAddress)
        </label>
    </li>
    <li>
        <button type="submit">Save</button>
    </li>
</ul>

@{Html.EndForm();}

JsConcepts/JsConcepts/Views/Contacts/Index.cshtml
@using Model.Projections
@model IEnumerable<ContactBriefInfo>
@{
    ViewBag.Title = "Contacts";
    Layout = "~/Views/Shared/MainLayout.cshtml";
}

<h2>Contacts</h2>

@Html.ActionLink("New Contact", "Create", "Contacts")

<table>
    <thead>
        <tr>
            <th>
                First Name
            </th>
            <th>
                Last Name
            </th>
            <th>
                Company
            </th>
            <th>
                Options
            </th>
        </tr>
    </thead>
    <tbody>
    @foreach (ContactBriefInfo contact in Model) { 
        <tr>
            <td>
                @contact.FirstName
            </td>
            <td>
                @contact.LastName
            </td>
            <td>
                @contact.Company
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", "Contacts", new { id = contact.Id }, new { })
                |
                @Html.ActionLink("Delete", "Delete", "Contacts", new { id = contact.Id }, new { })
            </td>
        </tr>
    }
        </tbody>
</table>

JsConcepts/JsConcepts/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home";
    Layout = "~/Views/Shared/MainLayout.cshtml";
}

<h2>App Sections</h2>
<ul>
    <li>
        @Html.ActionLink("Manage Contacts", "Index", "Contacts")
    </li>
    <li>
        @Html.ActionLink("Browse Contacts", "Index", "Browse")
    </li>
</ul>

JsConcepts/JsConcepts/Views/Shared/MainLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title | JS vs C# with ASP.NET MVC 4.5</title>
    <link href="~/css/main.css" type="text/css" rel="stylesheet" />
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>